"""
Test script for the inference API
"""

import requests
import json

# ============================================================================
# CONFIGURATION
# ============================================================================

API_URL = "http://localhost:5000"  # Change this for deployed API

# ============================================================================
# TEST FUNCTIONS
# ============================================================================

def test_health():
    """Test health endpoint"""
    response = requests.get(f"{API_URL}/health")
    print("Health Check:")
    print(json.dumps(response.json(), indent=2))
    print()

def test_chat(question):
    """Test chat endpoint"""
    response = requests.post(
        f"{API_URL}/chat",
        json={"question": question}
    )
    print(f"Question: {question}")
    print(f"Answer: {response.json()['answer']}")
    print()

def test_generate(prompt):
    """Test generate endpoint"""
    response = requests.post(
        f"{API_URL}/generate",
        json={"prompt": prompt, "max_tokens": 150}
    )
    print(f"Prompt: {prompt}")
    print(f"Response: {response.json()['response']}")
    print()

# ============================================================================
# RUN TESTS
# ============================================================================

if __name__ == "__main__":
    print("="*80)
    print("TESTING API")
    print("="*80)
    
    # Test health
    test_health()
    
    # Test chat
    test_chat("Who was Sri Vijaya Rajasinha?")
    test_chat("What is Sri Dalada Maligawa?")
    test_chat("Tell me about the Esala Perahera")

    print("="*80)
print("✅ All tests complete!")

---

## **8. README.md**
Will be auto-generated by the `create_model_card()` function when you upload to HuggingFace.

---

## **Usage Instructions:**

1. **Update configurations** in all files with your actual values
2. **Run deployment**: `python deploy_script.py`
3. **Test locally**: `python inference_api.py` then `python test_api.py`
4. **Deploy to HuggingFace Spaces**: Upload `app.py` and `requirements.txt`

All files are ready to use! Just update the configuration values and run the deployment script.